name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Application
        run: |
          set -e

          cd /opt/kernaleye/nexus

          git pull origin main

          docker pull node:22

          docker compose up -d --build